scripts/install_mhnserver_unattended.sh
server/generateconfig.py
server/requirements.txt

Added options to give the ability for an unattended, automatic install in the case of using ansible or a script to install the MHN server.
The option for prompts is still default. Adding the command 'unattended' as the first argument will require the use of arguments to specify options.
```
usage: generateconfig.py unattended [-h] -e EMAIL -p PASSWORD [-b BASE_URL]
[-y HONEYMAP_URL] [-m MAIL_SERVER]
[-s MAIL_PORT] [--mail_tls] [--mail_ssl]
[--mail_user MAIL_USER]
[--mail_pass MAIL_PASS]
[--mail_sender MAIL_SENDER]
[-l LOG_FILE_PATH] [-d]
optional arguments:
-h, --help            show this help message and exit
-e EMAIL, --email EMAIL
Superuser email address
-p PASSWORD, --password PASSWORD
Superuser password
-b BASE_URL, --base_url BASE_URL
Server base url
-y HONEYMAP_URL, --honeymap_url …
```

Unattended install

---

server/mhn/common/clio.py
server/mhn/templates/ui/dashboard.html
server/mhn/ui/views.py

This adds in support for the switch I'm proposing in mnemosyne for payload from string to JSON object in clio.py. Also noticed in get_payloads I was passing a list from the generator returned by the ResourceMixin, changed that to pass a generator on. 
Decided to add stats for Top Sensors and Top Honey Pots to the Dashboard. Helpful for me at least.

support for JSON Payload in hpfeed collection; Payload performance; Dashboard Additions

---

scripts/install_elk_raw_hpfeeds.sh

Sorry @aabed, I meant to check this in with my original PR.  The change to use hpfeeds-logger to write JSON and logstash to read the JSON file was so ELK could use the same normalized output that the MHN splunk app uses so the dashboards could be identical.  
The logstash-hpfeeds-input reads the raw records from hpfeeds which are not normalized.  I realize some people will want this instead we will will have both.

restored the original install_elk.sh as install_elk_raw_hpfeeds.sh

---

scripts/deploy_kippo.sh
server/mhn/__init__.py

The change is to replace "reload ssh" with "service ssh restart". The latter
works on both systems. It does not interrupt any open sessions.
This solves the same issue as https://github.com/threatstream/mhn/pull/133 but in a slightly different way.

Changed Kippo deploy script to be compatible with boh Ubuntu and Raspberry Pi

---

scripts/deploy_kippo.sh

Makes sure the sysctl setting and the iptables are saved across reboots. This is needed on both Ubuntu and Raspbian devices.

Make IP-forwarding persistent

---

server/mhn/auth/views.py

Replaced time based hash salt with random based hash salt. Preventing an unauthorized user with a known email address from triggering a password reset then guessing the milliseconds via brute force. While it took a little while against my own system as a poc, this style of attack did work in a reasonable amount of time.

Improved randomness in email reset hash

---

install.sh
scripts/deploy_dionaea.sh
scripts/install_honeymap.sh
scripts/install_hpfeeds.sh
scripts/install_mhnserver.sh
scripts/install_mnemosyne.sh
scripts/install_mongo.sh
scripts/install_python2.7.sh
scripts/install_sqlite.sh
scripts/install_supervisord.sh

Some versions of Centos 6.7 have installation problems related to $PATH not including necessary directories. To fix this issue, I defined $PATH at the start of the RHEL section the default in my VM.

PATH updated in install scripts for Centos 6.7

---

scripts/deploy_wordpot.sh

Fixes error on Ubuntu 14.04 when deploying wordpot. Error below:
+ supervisorctl update
error: <class 'socket.error'>, [Errno 2] No such file or directory: file: /usr/lib/python2.7/socket.py line: 224
The fix is to start supervisorctl (which is not started automatically when deploying wordpot).

Fixed Wordpot Deploy Script

---

server/requirements.txt

Was unable to install (after getting the MongoDB issues sorted) and had to adjust this to get it to build.

Updated uWSGI to version 2.0.14 for Ubuntu 16.04.1 compatibility.

---

scripts/deploy_shockpot.sh
scripts/deploy_wordpot.sh
scripts/install_honeymap.sh
scripts/install_hpfeeds.sh

Also updates wordpot and shockpot deploy scripts to install python, required for Ubuntu 16.04 where python isn't installed from base install.
Lastly, also update install script for honeymap to use latest Go version, 1.9.

Fixes #441

---

server/generateconfig.py

honeymap_url displays [:3000] and therefore computes the wrong configuration if default is accepted.

derive server base_url before passing to honeymap url

---

scripts/deploy_amun.sh

Previously it would checkout the dev branch of amun and do some tweaking. Changing branches is no longer needed and the 'hexdumps' directory already exists.

Fix amun install script to use master branch

---

scripts/deploy_glastopf.sh

Checks for Ubuntu 14 or 16 and warns if neither. Now installs on both.

Add support for Ubuntu 16.04 to Glastopf install

---

scripts/install_mongo.sh

Allows MHN to be running on reboot.

Enable mongodb on start for Ubuntu

---

scripts/install_hpfeeds.sh

Fixes error "urllib2.HTTPError: HTTP Error 403: Forbidden" caused by using HTTP
instead of HTTPS

Pull evnet from the threatstream fork

---

scripts/install_hpfeeds-logger-arcsight.sh
scripts/install_hpfeeds-logger-json.sh
scripts/install_hpfeeds-logger-splunk.sh

Version 0.7.2 is no longer installable due to using HTTP rather than HTTPS

Update hpfeeds-logger to version 0.7.3

---

scripts/deploy_amun.sh
scripts/deploy_conpot.sh
scripts/deploy_cowrie.sh
scripts/deploy_dionaea.sh
scripts/deploy_elastichoney.sh
scripts/deploy_glastopf.sh
scripts/deploy_p0f.sh
scripts/deploy_shockpot.sh
scripts/deploy_snort.sh
scripts/deploy_suricata.sh
scripts/deploy_wordpot.sh
server/mhn/__init__.py

This prevents sensors from being registered on the server before their install completes. In many cases, an install might fail for various reasons yet the sensor is prematurely registered, clogging up the MHN server's list of running sensors with false entries.
Fixes #188

Move sensor registration to after sensor install completes

---

scripts/deploy_cowrie.sh

Fixes #487 by specifying cryptography version in requirements.txt file.

Fix cowrie install on Ubuntu 14.04. Fixes #487

---

server/mhn/common/clio.py
server/requirements.txt

This fixes the Ubuntu 18 install. Pymongo python library has been updated across all platforms. Minimal testing has been done but it could definitely use more.

Mongodb fix for Ubuntu 18

---

scripts/deploy_cowrie.sh

Previously, we were trying to write to $COWRIE_HOME/log/cowrie.out but /log has been moved and changed to $COWRIE_HOME/var/log/cowrie/

Update cowrie deploy script to properly store log file.

---

server/mhn/static/js/main.js
server/mhn/templates/ui/add-sensor.html

The process for adding a new external sensor was fairly complicated when it didn't have to be, really.
The add-sensor view made the same api-call that the registration script made, so the sensor was already registered. The ony problem was that we didn't have the secret, but that is very easy to add.
Now the process to add an external sensor is as simple as going to the add-sensor view, filling the form and then configuring the sensor with the values provided.

Add Secret field on add-sensor view

---

server/mhn/ui/utils.py

When viewing the `/ui/attacks` page, MHN sends all the IP to `geospray.threatstream.com` to get the IP's countries in order to display the correct flag. 
Here I suggest to use the GeoIP mmdb downloaded during the installation in `scripts/install_honeymap.sh` in order to resolve IP. This commit will
- render the page quicker,
- render the page even if `geospray.threatstream.com` is unreachable / not working,
- prevent to share MHN collected IP with others.
Closes threatstream/mhn#694 and threatstream/mhn#707

Resolve IP country locally

---

scripts/install_elk.sh

Script updated and working.
A few things:
- Make sure the system MHN is installed on has enough RAM and disk space. 3GB of RAM and 10GB of disk seem to be the minimum (tested with only one Sensor though). For instance, MHN installed on an Ubuntu server with only the basic (mail and SSH) along with ELK takes around 8.8GB of disk.
- I was unable to fix the following warnings in Logstash:
- `Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>7}`. Not sure where this type is taken from, maybe from the log.
- `[org.logstash.instrument.metrics.gauge.LazyDelegatingGauge][main] A gauge metric of an unknown type (org.jruby.specialized.RubyArrayOneObject) has been create for key: cluster_uuids. This may result in invalid …

Updates ELK Install to use 7.x versions - Ref #740

---

server/requirements.txt

**What**: Broken dependency
**Where**: install_mhnserver.sh
**Error description**
running install_mhnserver.sh returnes an error:
+ python initdatabase.py
Traceback (most recent call last):
File "initdatabase.py", line 1, in <module>
from mhn import create_clean_db
File "/opt/mhn/server/mhn/__init__.py", line 5, in <module>
from flask_security import Security, SQLAlchemyUserDatastore
File "/opt/mhn/env/local/lib/python2.7/site-packages/flask_security/__init__.py", line 13, in <module>
from .core import Security, RoleMixin, UserMixin, AnonymousUser, current_user
File "/opt/mhn/env/local/lib/python2.7/site-packages/flask_security/core.py", line 25, in <module>
from .forms import LoginForm, ConfirmRegisterForm, RegisterForm, \
File "/opt/mhn/env/local/lib/python2.7/site-packages/flask_securit …

Fixed install_mhnserver.sh issue with url_encode import.

---

server/requirements.txt

The current version of Flask-SQLAlchemy in server/requirements.txt is set to 2.3.2 but it will produce this error on a terminal due to its incompatibility: 
To fix this, its version should be changed to 2.5.1 according to the issue from flask-sqlalchemy's repo:
#https://github.com/pallets/flask-sqlalchemy/issues/910#issuecomment-802098285

make a change to a version of Flask-SQLAlchemy

---

Dockerfile
scripts/docker_expect.sh

- Currently MHN does not work with ubuntu 20.04. Docker image changed from latest to 18.04. 
-  Docker installation does not complete because there is no answer in docker_expect.sh file for UFW configuration. Proper expect statement added.

Improve docker support

---

server/mhn/api/views.py

Adds token authentication requirement for the update sensor endpoint to prevent unauthenticated modification of sensor name and hostname, as raised in #809

Add token authentication to update sensor endpoint

---

scripts/deploy_amun.sh

An attempted increase the the max number of open files for all Linux systems is causing the deployment to fail. My testing shows that `9223372036854775807` is the current default amount.

Remove max open files increase
